"""auto-vote

Revision ID: 338f1d204a77
Revises: 80118b21da55
Create Date: 2025-02-02 13:16:20.513109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338f1d204a77'
down_revision: Union[str, None] = '80118b21da55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_uuid', sa.Integer(), nullable=False),
    sa.Column('post_uuid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_uuid'], ['posts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_uuid', 'post_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
