name: Build and Deploy Code

on: 
  push:
    branches: 
      - "main"
      - "feature/test"
      - "master"
  
  pull_request:
    branches: ["devel", "master"]

# Accessible to all jobs
# env:
#   DATABASE_HOSTNAME: localhost

jobs:
  job1:
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PWD: postgres
      DB_NAME: fastapi
      DB_USERNAME: postgres
      SECRET_KEY: a066e136d8ad1f8abada99bc47228273ca4b0f01bb699540fa6326b57110dc1a
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Say hi to kris
        run: echo "Hi Kris!"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -v -s  
